[versions]
accompanistSystemuicontroller = "0.31.1-alpha"
accompanistSystemuicontrollerVersion = "0.20.0"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.9.3"
androidx-lifecycle = "2.8.3"
compose-plugin = "1.7.0"
gson = "2.10.1"
json = "20210307"
kotlin = "2.0.21"
lifecycleRuntimeKtx = "2.8.7"
material = "1.7.5"
material3Android = "1.3.1"
multidex = "2.0.1"
navigationCompose = "2.8.4"
navigationComposeVersion = "2.7.0-alpha07"
resourcesVersion = "0.24.5"
ui = "1.7.5"
uiToolingPreview = "1.7.5"
uiAndroid = "1.7.5"
activityKtx = "1.9.3"
core = "1.15.0"
annotationJvmVersion = "1.9.1"
jetbrainsKotlinJvm = "1.9.0"
cocoapodsVersion = "2.1.20"

[libraries]
accompanist-systemuicontroller-v0311alpha = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "uiToolingPreview" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontrollerVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
material = { module = "androidx.compose.material:material", version.ref = "material" }
androidx-ui-android = { group = "androidx.compose.ui", name = "ui-android", version.ref = "uiAndroid" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvmVersion" }
resources = { module = "dev.icerock.moko:resources", version.ref = "resourcesVersion" }
resourcesCompose = { module = "dev.icerock.moko:resources-compose", version.ref = "resourcesVersion" }
resourcesTest = { module = "dev.icerock.moko:resources-test", version.ref = "resourcesVersion" }

resourcesGradlePlugin = { module = "dev.icerock.moko:resources-generator", version.ref = "resourcesVersion" }

[plugins]
androidApplication = { id = "com.android.application"}
androidLibrary = { id = "com.android.library"}
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "cocoapodsVersion"}